apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017 #porta de escuta 
      targetPort: 27017 #encaminha para Pod "mongo"
  #type: não tem! (ClusterIP eh o Padrão): acessível apenas dentro do Pod
