apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo 
          image: mongo:3.6.17-xenial        
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db #path dentro do conteiner       
      volumes: 
        - name: storage #nome do volume
          persistentVolumeClaim:
            claimName: mongo-pvc #metadata.name  do recurso "PersistentVolumeClaim"  em "mongoApp-Volume.yaml"
